[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = [
    "babel.*",
    "pytz.*",
    "sklearn.*",
    "plotly.*",
    "streamlit.*",
    "graphene.*",
    "graphene_sqlalchemy.*",
    "starlette.*",
    "psutil.*",
    "prometheus_client.*",
    "playwright.*",
    "selenium.*",
    "aiohttp.*",
    "httpx.*",
    "redis.*",
    "pandas.*",
    "numpy.*",
    "matplotlib.*",
    "seaborn.*",
    "joblib.*",
    "xgboost.*",
    "lightgbm.*",
    "optuna.*",
    "prophet.*",
    "statsmodels.*",
    "tensorflow.*",
    "altair.*",
    "bokeh.*",
    "websockets.*",
    "pytest.*",
    "pytest_asyncio.*",
    "pytest_cov.*",
    "black.*",
    "isort.*",
    "flake8.*",
    "pre_commit.*",
]
ignore_missing_imports = true
